### ISSUE TITLE
Bagaimana cara run program ini? 

### ISSUE THREAD

**Issue by fajarwahyu99** [riochr17/Analisis-Sentimen-ID#2]
Bagaimana cara run program ini? 
Cara crawling datanya bagaimana?

**Comment by riochr17** [comment]
![ss](https://image.ibb.co/jNOJWd/Screen_Shot_2018_06_30_at_18_33_27.png)

ini contoh mulai clone sampai running

**Comment by riochr17** [comment]
Crawling data tidak dilakukan disini. Mohon baca readme dengan jelas terlebih dahulu sebelum bertanya. Data twitter diambil dari salah satu repository yang ada pada credit readme.
