### ISSUE TITLE
#ASK 

### ISSUE THREAD

**Issue by faqisyadid** [riochr17/Analisis-Sentimen-ID#3]
Selamat sore ka, maaf mau tanya lagi ka, maaf bnyak saya tanya ya ka, krna saya sedang bljr MLP sedikit 
 sedikit, dan  saya mash blom paham dengan kode di bawah ini ka. mksd dari indim itu kegunaan apa ya ka? dan angka 0.39 itu untuk apa ya ka?
terimkash

indim = len(X[0])
	indim = 300 if indim > 300 else indim

	model.add(Dense(units=int(0.39 * indim), activation='tanh', input_dim=indim))

**Comment by riochr17** [comment]
@faqisyadid 
indim itu representasi dimensi input, disini saya membatasi maksimal input dimensi sebesar 300, sehingga:
```layer pertama sebesar <indim> node```
```layer kedua sebesar <indim> * 0.39 node```
```layer ketiga sebesar 5 node ```
```layer keempat / ouput sebesar 1 node```

angka 0.39 hanya heuristik untuk eksperimen, bisa diganti dengan angka lain, angka 0.39 akan menentukan banyaknya node pada layer kedua.

misal input training memiliki dimensi `len(X[0]) = 290`, maka node disetiap layer adalah:
```290 -> 290*0.39 -> 5 -> 1```
```290 -> 113 -> 5 -> 1```


https://github.com/riochr17/Analisis-Sentimen-ID/blob/516d11ba66002cf6580ae4598e980ca71501df0a/main.py#L28-L33

**Comment by faqisyadid** [comment]
ka brrti indim itu di dapat dari hasil tfidf? mendapatkan 300 indim itu berdasarkan nilai tf-idf tertinggi ya ka?
